services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${CONTAINER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${CONTAINER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${CONTAINER_POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
