version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: fiap-hackaton
      POSTGRES_PASSWORD: our-strong-password-1205132
      POSTGRES_DB: fiap-hackaton
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    container_name: '${LOCALSTACK_DOCKER_NAME:-localstack-main}'
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
      - '127.0.0.1:4510-4559:4510-4559' # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - DEFAULT_REGION=${DEFAULT_REGION:-us-east-1}
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      ls:
        # Set the container IP address in the 10.0.2.0/24 subnet
        ipv4_address: 10.0.2.20
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '1024M'
networks:
  ls:
    ipam:
      config:
        # Specify the subnet range for IP address allocation
        - subnet: 10.0.2.0/24

volumes:
  postgres_data:
