services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: fiap-hackaton
      POSTGRES_PASSWORD: our-strong-password-1205132
      POSTGRES_DB: fiap-hackaton
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
